#!/bin/bash

MACHINE_TYPE=c2-standard-4
INSTANCE_NAME=lineage-dev-$(date '+%s')
DISK_NAME=${INSTANCE_NAME}
IMAGE_NAME=$1

print_usage(){
    echo "create-instance <image name>"
}

if [[ -z "${IMAGE_NAME}" ]]; then
    print_usage
    exit 1
fi

gcloud \
  beta \
  compute \
  --project=yasunori-horikoshi-sandbox \
  instances \
  create \
  ${INSTANCE_NAME} \
  --zone=asia-northeast1-b \
  --machine-type=${MACHINE_TYPE} \
  --subnet=default \
  --network-tier=PREMIUM \
  --maintenance-policy=MIGRATE \
  --service-account=696806942203-compute@developer.gserviceaccount.com \
  --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
  --image=${IMAGE_NAME} \
  --image-project=yasunori-horikoshi-sandbox \
  --boot-disk-size=20GB \
  --boot-disk-type=pd-balanced \
  --boot-disk-device-name=${DISK_NAME} \
  --reservation-affinity=any
